# Generated by Django 5.0.7 on 2024-07-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('duration', models.TimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('0', 'Easy'), ('1', 'Moderate'), ('2', 'Hard')], max_length=1)),
            ],
        ),
    ]
