# Generated by Django 5.0.7 on 2024-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogs', '0002_alter_jogs_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogs',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
