# Generated by Django 5.0.7 on 2024-07-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogs', '0003_alter_jogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogs',
            name='date',
            field=models.DateField(),
        ),
    ]
