# Generated by Django 5.0.7 on 2024-07-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogs', '0005_alter_jogs_difficulty_alter_jogs_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogs',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Easy'), ('1', 'Moderate'), ('2', 'Hard')], max_length=1),
        ),
    ]
