# Generated by Django 5.0.7 on 2024-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogs', '0007_alter_jogs_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogs',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Easy'), ('1', 'Hard')], max_length=1),
        ),
    ]
